{{- if eq .Values.mode "operator" }}
{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clair.operator.serviceAccountName" . }}
  labels:
    {{- include "clair.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
