{{- if and (or (eq .Values.mode "combo") (eq .Values.mode "distributed")) .Values.postgresql.enabled }}
{{- $dbPassword := include "clair.dbPassword" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clair.fullname" . }}-postgresql
  labels:
    {{- include "clair.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ $dbPassword | quote }}
{{- end }}
