{{- if and (eq .Values.mode "deployment") .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clair.fullname" . }}-postgresql
  labels:
    {{- include "clair.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    {{- include "clair.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
{{- end }}
