{{- if eq .Values.mode "distributed" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clair.fullname" . }}-indexer
  labels:
    {{- include "clair.labels" . | nindent 4 }}
    app.kubernetes.io/component: indexer
spec:
  type: ClusterIP
  selector:
    {{- include "clair.indexer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: indexer
  ports:
    - name: http
      port: 6060
      targetPort: http
      protocol: TCP
    - name: introspection
      port: 8089
      targetPort: introspection
      protocol: TCP
{{- end }}
