{{- if and (eq .Values.mode "distributed") .Values.distributed.notifier.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clair.fullname" . }}-notifier
  labels:
    {{- include "clair.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifier
spec:
  type: ClusterIP
  selector:
    {{- include "clair.notifier.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: notifier
  ports:
    - name: http
      port: 6060
      targetPort: http
      protocol: TCP
    - name: introspection
      port: 8089
      targetPort: introspection
      protocol: TCP
{{- end }}
