{{- if and (eq .Values.mode "combo") .Values.combo.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "clair.fullname" . }}
  labels:
    {{- include "clair.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "clair.fullname" . }}
  minReplicas: {{ .Values.combo.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.combo.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.combo.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
