{{- if and (eq .Values.mode "deployment") .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "clair.fullname" . }}
  labels:
    {{- include "clair.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "clair.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: clair
{{- end }}
